# flake8: noqa

# import apis into api package
from .account_api import AccountApi
from .broadcast_group_api import BroadcastGroupApi
from .channel_plan_api import ChannelPlanApi
from .dhcp_option_api import DHCPOptionApi
from .dashboard_api import DashboardApi
from .device_api import DeviceApi
from .dpi_app_api import DpiAppApi
from .dpi_group_api import DpiGroupApi
from .dynamic_dns_api import DynamicDNSApi
from .firewall_group_api import FirewallGroupApi
from .firewall_rule_api import FirewallRuleApi
from .heat_map_api import HeatMapApi
from .heat_map_point_api import HeatMapPointApi
from .hotspot2_conf_api import Hotspot2ConfApi
from .hotspot_op_api import HotspotOpApi
from .hotspot_package_api import HotspotPackageApi
from .map_api import MapApi
from .media_file_api import MediaFileApi
from .network_api import NetworkApi
from .port_forward_api import PortForwardApi
from .port_profile_api import PortProfileApi
from .radius_profile_api import RADIUSProfileApi
from .routing_api import RoutingApi
from .schedule_task_api import ScheduleTaskApi
from .setting_auto_speedtest_api import SettingAutoSpeedtestApi
from .setting_baresip_api import SettingBaresipApi
from .setting_broadcast_api import SettingBroadcastApi
from .setting_connectivity_api import SettingConnectivityApi
from .setting_country_api import SettingCountryApi
from .setting_doh_api import SettingDohApi
from .setting_dpi_api import SettingDpiApi
from .setting_element_adopt_api import SettingElementAdoptApi
from .setting_ether_lighting_api import SettingEtherLightingApi
from .setting_global_ap_api import SettingGlobalApApi
from .setting_global_switch_api import SettingGlobalSwitchApi
from .setting_guest_access_api import SettingGuestAccessApi
from .setting_ips_api import SettingIpsApi
from .setting_lcm_api import SettingLcmApi
from .setting_locale_api import SettingLocaleApi
from .setting_magic_site_to_site_vpn_api import SettingMagicSiteToSiteVpnApi
from .setting_mgmt_api import SettingMgmtApi
from .setting_network_optimization_api import SettingNetworkOptimizationApi
from .setting_ntp_api import SettingNtpApi
from .setting_porta_api import SettingPortaApi
from .setting_radio_ai_api import SettingRadioAiApi
from .setting_radius_api import SettingRadiusApi
from .setting_rsyslogd_api import SettingRsyslogdApi
from .setting_snmp_api import SettingSnmpApi
from .setting_super_cloudaccess_api import SettingSuperCloudaccessApi
from .setting_super_events_api import SettingSuperEventsApi
from .setting_super_fwupdate_api import SettingSuperFwupdateApi
from .setting_super_identity_api import SettingSuperIdentityApi
from .setting_super_mail_api import SettingSuperMailApi
from .setting_super_mgmt_api import SettingSuperMgmtApi
from .setting_super_sdn_api import SettingSuperSdnApi
from .setting_super_smtp_api import SettingSuperSmtpApi
from .setting_teleport_api import SettingTeleportApi
from .setting_usg_api import SettingUsgApi
from .setting_usw_api import SettingUswApi
from .spatial_record_api import SpatialRecordApi
from .tag_api import TagApi
from .user_api import UserApi
from .user_group_api import UserGroupApi
from .virtual_device_api import VirtualDeviceApi
from .wlan_api import WLANApi
from .wlan_group_api import WLANGroupApi
